### ISSUE TITLE
Creating Vector Index (IVF) error: "expected 1536 dimensions, not 768"

### ISSUE THREAD

**Issue by CarteKiwi** [Azure-Samples/Cosmic-Food-RAG-app#108]
**Describe the bug**
Hello,
I tried to execute the notebook using my freshly created resources on Azure.

This line cause error:
`vector_store.create_index(num_lists,  similarity_algorithm, kind, m, ef_construction)`

Output:
`OperationFailure: expected 1536 dimensions, not 768, full error: {'ok': 0.0, 'errmsg': 'expected 1536 dimensions, not 768', 'code': 2, 'codeName': 'BadValue'}`

**To Reproduce**

1. Create a "Azure Cosmos DB for MongoDB (vCore)" ressource on Azure (FreeTier) (Public Access)
2. Create a "Azure OpenAI" ressource on Azure
3. Deploy model in "Azure Open AI Studio" using model "text-embedding-ada-002" (no dynamic quota and DefaultV2)
4. Set variables (Api Key, Endpoint, dbname and collection) to connect to MongoDB and openai service
5. Execute notebook

**Desktop:**

- OS: Windows 11
- Soft: Visual Studio Code
- Version: Python 3.12.3

**Additional context**
I can't use VECTOR_HNSW in Free Tier.
If I set dimensions during AzureOpenAIEmbeddings instantiation, I got same error.
If I set dimensions = X, I got error: expected X dimensions, not 768
If I set dimensions = 768, I got error: expected 768 dimensions, not 1536

Thanks for your help.

**Comment by john0isaac** [comment]
Hey @CarteKiwi,
Thank you for reporting.

Are you using the latest version of this repo?
we removed the HNSW index so, you shouldn't be getting any errors related to it.
If you are not using the latest version please try to update the code and check again.

If you are using the latest version then I will have to ask a colleague to confirm that vector search with IVF is supported in the free tier. (I'm not sure that it's supported in the free tier)

**Comment by john0isaac** [comment]
Also, Regarding the error "768" we have not set this anywhere in our code so please revert to the original code and show me the initial error without any fixes.

**Comment by CarteKiwi** [comment]
> Also, Regarding the error "768" we have not set this anywhere in our code so please revert to the original code and show me the initial error without any fixes.

Using original code, not setting 768 anywhere, I got the error:
`OperationFailure: expected 1536 dimensions, not 768, full error: {'ok': 0.0, 'errmsg': 'expected 1536 dimensions, not 768', 'code': 2, 'codeName': 'BadValue'}`

**Comment by CarteKiwi** [comment]
> Hey @CarteKiwi, Thank you for reporting.
> 
> Are you using the latest version of this repo? we removed the HNSW index so, you shouldn't be getting any errors related to it. If you are not using the latest version please try to update the code and check again.
> 
> If you are using the latest version then I will have to ask a colleague to confirm that vector search with IVF is supported in the free tier. (I'm not sure that it's supported in the free tier)

Thanks for your prompt reply !
Yes, I'm using latest version. But had to change the "OpenAI Client variables" that seems to be obsolete.

Replacing this :
```
import openai

openai.api_type = os.getenv("OPENAI_API_TYPE", "azure")
openai.base_url = os.getenv("AZURE_OPENAI_ENDPOINT", "https://<YOUR-OPENAI-DEPLOYMENT-NAME>.openai.azure.com/")
openai.api_version = os.getenv("OPENAI_API_VERSION", "2023-09-15-preview")
openai.api_key = os.getenv("OPENAI_API_KEY", "<YOUR-DEPLOYMENT-KEY>")
```

To this:
```
os.environ["AZURE_OPENAI_ENDPOINT"] = ("https://<MYNAME>.openai.azure.com/")
os.environ["AZURE_OPENAI_API_KEY"] = "<MYKEY>"
```

**Comment by john0isaac** [comment]
> > Also, Regarding the error "768" we have not set this anywhere in our code so please revert to the original code and show me the initial error without any fixes.
> 
> Using original code, not setting 768 anywhere, I got the error: `OperationFailure: expected 1536 dimensions, not 768, full error: {'ok': 0.0, 'errmsg': 'expected 1536 dimensions, not 768', 'code': 2, 'codeName': 'BadValue'}`

the error clearly states that you are trying to use `dimension = 768` here `expected 1536 dimensions, not 768` can you revert this back to 1536?

**Comment by john0isaac** [comment]
sorry for the delay in getting back to you on this.
I'm working on it not and will get back to you with a resolution in the next couple of hours.

**Comment by john0isaac** [comment]
I just created a fresh deployment and tried replicating your issue but I didn't face the same problem as you have been facing.

My suggestion is that you try updating langchain, langchain and pull the latest version of the repo and try it.

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/9971683b-aa31-4401-990a-af1650d862a8">
