### ISSUE TITLE
The web service unavailable after deploying by azd.

### ISSUE THREAD

**Issue by zedy-wj** [Azure-Samples/Cosmic-Food-RAG-app#99]
**Describe the issue:**
It seems normal after executing the command: `azd up`, 
![image](https://github.com/user-attachments/assets/3fe5c31b-6840-4aff-9ff4-3a903a690121)

but when click the endpoint after `azd up` and enter the question, service is unavailable.
![image](https://github.com/user-attachments/assets/57c83bb0-6498-46c7-b667-e83ae3ec219c)

**Repro steps:**
1. Open in GitHub Codespace.
2. Run `azd auth login`
3. Run `azd init`
4. Run `azd up`
5. Click the endpoint after deploying.

**Environment:**

- Azd version: azd version 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)

- OS: Codespaces

**Expected behavior:**
All services are available after deploying by `azd up`

@hemarina and @john0isaac for notification.

**Comment by john0isaac** [comment]
@zedy-wj can you try to run the command that adds the data?
We don't automatically populate the database with the provided sample of data this step has to be done manually after the deployment. See this https://github.com/Azure-Samples/Cosmic-Food-RAG-app#add-the-data

**Comment by zedy-wj** [comment]
> Thank you for testing this!
> 
> @zedy-wj can you try to run the command that adds the data? We don't automatically populate the database with the provided sample of data this step has to be done manually after the deployment. See this https://github.com/Azure-Samples/Cosmic-Food-RAG-app#add-the-data

I also tried providing some data according to the ReadMe, but encountered the following problems:
![image](https://github.com/user-attachments/assets/5d76f13b-e4c4-49f8-8fb1-5d47d7b59bb8)

This error seems to be that the default `SKU` of the cluster does not meet the requirements?

**Comment by john0isaac** [comment]
Ok that's an actual error let me fix it.
We are using Index HNSW which I guess is not currently supported by the M25 SKU.
I will change it to IVF Index and it should work.

**Comment by john0isaac** [comment]
@khelanmodi can you confirm whether the M25 SKU supports creating HNSW index or not.
And if not which sku supports the HNSW index? Or is it not public yet?
